# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Rilla Khaled"
email: rilla.khaled@concordia.ca
description: > # this means to ignore newlines until "baseurl:"
  Rilla Khaled is an Associate Professor in the Department of
  Design and Computation Arts at Concordia University in Montréal.
  She is also the Director of the Technoculture, Art, and Games (TAG)
  Research Centre in the Milieux Institute for Arts, Culture, and Technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rillakhaled.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rillakhaled
github_username:  rillakhaled

# Build settings
markdown: kramdown
theme: minima
date_format: "%-d %B %Y"
future: false

plugins:
 - jekyll-feed
 # - jekyll-archives

exclude:
 - Gemfile
 - Gemfile.lock
 - node_modules
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
 - _site/

    # Exclude from processing.
    # The following items will not be processed, by default. Create a custom list
    # to override the default setting.
    # exclude:
    #   - Gemfile
    #   - Gemfile.lock
    #   - node_modules
    #   - vendor/bundle/
    #   - vendor/cache/
    #   - vendor/gems/
    #   - vendor/ruby/
